@Library('jenkins-ssh-executor') _

pipeline {
    agent any
    options {
        timestamps()
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    environment {
        APP_NAME = 'wesman'
    }

    stages {
        stage('Checkout Repository') {
            steps {
                checkout scm
            }
        }
       stage('Build Check') {
            when {
                branch pattern: '^(?!main$|develop$).*$', comparator: 'REGEXP'
            }
            steps {
                echo "🔍 Performing build check for branch ${env.BRANCH_NAME}..."
                sh 'npm ci'
                sh 'npm run build'
            }
        }

        stage('Deploy to VPS') {
            when {
                anyOf {
                    branch 'main'
                    branch 'develop'
                }
            }
            steps {
                script {
                    echo "📦 Deploying ${APP_NAME} on branch ${env.BRANCH_NAME}..."

                    def deployScript = load('.groovy/Deployment.groovy')
                    sshagent(credentials: ['VPS_CREDENTIAL']) {
                        deployScript(env.BRANCH_NAME, APP_NAME, env.VPS1_USER, env.VPS1_HOST)
                    }
                }
            }
        }
    }

    post {
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
